### ISSUE TITLE
Getting below error in go get

### ISSUE THREAD

**Issue by priyeshbhaskar** [jen20/hashiconf-raft#5]
# github.com/jen20/hashiconf-raft
pkg/mod/github.com/jen20/hashiconf-raft@v0.0.0-20181210160701-a93e7eb1cb59/main.go:103:20: cannot use log.New(log, "", 0) (type *log.Logger) as type hclog.Logger in assignment:
        *log.Logger does not implement hclog.Logger (missing Debug method)

**Comment by jen20** [comment]
Sorry, I'm not planning on keeping this repository updated., and it uses `dep` rather than Go modules. If you use the locked versions of dependencies I'd imagine things should still work.
